# Generated by Django 2.2.1 on 2019-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='member_pics')),
                ('position', models.CharField(max_length=40)),
                ('info', models.TextField()),
            ],
        ),
    ]
