# Generated by Django 2.2.1 on 2019-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='info',
            field=models.CharField(max_length=120),
        ),
    ]
